[platformio]
description = APRSPacketLib — Arduino-targeted APRS encode/decode

[env]
test_framework = unity

[env:native]
platform = native
build_flags =
	-std=gnu++17
	-DUNIT_TEST
	-DNATIVE_TEST_BUILD
	-I include
	-I src
	-I test/common
	-Wno-missing-template-arg-list-after-template-kw
lib_compat_mode = off
lib_deps =
	fabiobatsilva/ArduinoFake @ ^0.4.0
test_build_src = yes

[env:test-esp32s3dev]
platform = espressif32 @ 6.12.0
framework = arduino
board = esp32-s3-devkitc-1
board_build.mcu = esp32s3
build_flags =
	-DUNIT_TEST
	-I include
	-I src
	-I test/common
test_build_src = yes

[env:test-heltec_wireless_tracker]
extends = env:test-esp32s3dev
board_build.partitions = huge_app.csv
monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0
build_flags =
	${env:test-esp32s3dev.build_flags}
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
