// Verifies decodeBase91EncodedCourse / decodeBase91EncodedSpeed against
// vectors derived offline from APRS Protocol Reference v1.2 §9
// ("Compressed Position Report Data Formats", "Course/Speed"). The
// vectors live in test/common/decode_vectors.h and are regenerated by
// tools/gen_decode_vectors.py, which cross-checks each row against
// aprslib before emitting the header.
//
// These tests fail today because the decoders use String::toInt() on a
// single-character input, which returns 0 for any non-digit char (and
// the digit's decimal value, not its ASCII codepoint, otherwise). They
// pass with the patch in bug_report_l6_l7_decode_base91.md.
//
// The decoders are not in the public header — they are file-local
// helpers reached by processReceivedPacket (src/APRSPacketLib.cpp:630–
// 631) for any compressed packet with a course/speed-encoded c/s
// slot. We forward-declare them here; this is link-clean because
// test_build_src=yes pulls APRSPacketLib.cpp into the test binary.

#include <Arduino.h>
#include <unity.h>
#include <APRSPacketLib.h>
#include <stdio.h>

#include "decode_vectors.h"

namespace APRSPacketLib {
    int decodeBase91EncodedCourse(const String& course);
    int decodeBase91EncodedSpeed(const String& speed);
}

void setUp(void) {}
void tearDown(void) {}

static void test_decode_course_against_spec_vectors(void) {
    for (const auto& v : kCourseVectors) {
        int got = APRSPacketLib::decodeBase91EncodedCourse(String(v.encoded));
        char msg[64];
        snprintf(msg, sizeof(msg),
                 "byte 0x%02X expected %d degrees", (unsigned char)v.encoded, v.course_deg);
        TEST_ASSERT_EQUAL_INT_MESSAGE(v.course_deg, got, msg);
    }
}

static void test_decode_speed_against_spec_vectors(void) {
    for (const auto& v : kSpeedVectors) {
        int got = APRSPacketLib::decodeBase91EncodedSpeed(String(v.encoded));
        char msg[64];
        snprintf(msg, sizeof(msg),
                 "byte 0x%02X expected %d km/h", (unsigned char)v.encoded, v.speed_kmh);
        TEST_ASSERT_EQUAL_INT_MESSAGE(v.speed_kmh, got, msg);
    }
}

static void run_all(void) {
    RUN_TEST(test_decode_course_against_spec_vectors);
    RUN_TEST(test_decode_speed_against_spec_vectors);
}

#ifdef NATIVE_TEST_BUILD
int main(int /*argc*/, char ** /*argv*/) {
    UNITY_BEGIN();
    run_all();
    return UNITY_END();
}
#else
void setup(void) {
    Serial.begin(115200);
    delay(2000);
    UNITY_BEGIN();
    run_all();
    UNITY_END();
}

void loop(void) {
    delay(1000);
}
#endif
