// Decoder-side coverage for the Base91 (compressed) APRS position
// format — APRS Protocol Reference v1.2 §9 ('Compressed Position Report
// Data Formats').
//
// Vectors live in test/common/aprs_vectors.h and are regenerated by
// tools/gen_aprs_vectors.py, which cross-checks each row against
// aprslib before emitting the header.
//
// The c/s and altitude decoders are not in the public header — they
// are file-local helpers reached by processReceivedPacket
// (src/APRSPacketLib.cpp:626–631) for any compressed packet. We
// forward-declare them here; this is link-clean because
// test_build_src=yes pulls APRSPacketLib.cpp into the test binary.

#include <Arduino.h>
#include <unity.h>
#include <APRSPacketLib.h>
#include <stdio.h>
#include <string.h>

#include "aprs_vectors.h"

namespace APRSPacketLib {
    int decodeBase91EncodedCourse(const String& course);
    int decodeBase91EncodedSpeed(const String& speed);
    int decodeBase91EncodedAltitude(const String& altitude);
}

void setUp(void) {}
void tearDown(void) {}

// ---------- c/s slot ----------

static void test_decode_course_against_spec_vectors(void) {
    for (const auto& v : kCourseVectors) {
        int got = APRSPacketLib::decodeBase91EncodedCourse(String(v.encoded));
        char msg[64];
        snprintf(msg, sizeof(msg),
                 "byte 0x%02X expected %d°", (unsigned char)v.encoded, v.course_deg);
        TEST_ASSERT_EQUAL_INT_MESSAGE(v.course_deg, got, msg);
    }
}

static void test_decode_speed_against_spec_vectors(void) {
    for (const auto& v : kSpeedVectors) {
        int got = APRSPacketLib::decodeBase91EncodedSpeed(String(v.encoded));
        char msg[64];
        snprintf(msg, sizeof(msg),
                 "byte 0x%02X expected %d km/h", (unsigned char)v.encoded, v.speed_kmh);
        TEST_ASSERT_EQUAL_INT_MESSAGE(v.speed_kmh, got, msg);
    }
}

// ---------- lat / lon ----------

static void test_decode_lat_known_vectors(void) {
    for (const auto& p : kBase91FixedPoints) {
        float got = APRSPacketLib::decodeBase91EncodedLatitude(String(p.base91_lat));
        char msg[128];
        snprintf(msg, sizeof(msg),
                 "%s: lat \"%s\" expected %.6f got %.6f",
                 p.name, p.base91_lat, p.lat_deg, got);
        // Base91 lat resolution is ~1/380926 deg ≈ 0.3 m. 1e-4 deg
        // (~11 m) absorbs single-precision float drift.
        TEST_ASSERT_FLOAT_WITHIN_MESSAGE(1e-4f, p.lat_deg, got, msg);
    }
}

static void test_decode_lon_known_vectors(void) {
    for (const auto& p : kBase91FixedPoints) {
        float got = APRSPacketLib::decodeBase91EncodedLongitude(String(p.base91_lon));
        char msg[128];
        snprintf(msg, sizeof(msg),
                 "%s: lon \"%s\" expected %.6f got %.6f",
                 p.name, p.base91_lon, p.lon_deg, got);
        TEST_ASSERT_FLOAT_WITHIN_MESSAGE(1e-4f, p.lon_deg, got, msg);
    }
}

static void test_decode_lat_north_pole_exact(void) {
    // base91(0) → "!!!!". Spec: lat = 90 - 0/380926 = +90.0.
    float got = APRSPacketLib::decodeBase91EncodedLatitude(String("!!!!"));
    TEST_ASSERT_FLOAT_WITHIN(1e-5f, 90.0f, got);
}

static void test_decode_lat_south_pole_exact(void) {
    // base91(380926*180) = base91(68566680) → "{{!!".
    //   d3 = 68566680 / 91^3 = 90 ('{')
    //   d2 = 745290   / 91^2 = 90 ('{')
    //   d1 = 0                = 0 ('!')
    //   d0 = 0                = 0 ('!')
    // Decoded: 90 - (90*91^3 + 90*91^2)/380926 = 90 - 68566680/380926 = -90.
    float got = APRSPacketLib::decodeBase91EncodedLatitude(String("{{!!"));
    TEST_ASSERT_FLOAT_WITHIN(1e-5f, -90.0f, got);
}

// ---------- altitude ----------

static void test_decode_altitude_known_vectors(void) {
    for (const auto& p : kBase91FixedPoints) {
        // ('!','!') decodes to pow(1.002, 0) = 1 ft, which is the lib's
        // sentinel for "altitude not sent" — skip the zero-input vectors.
        if (p.altitude_ft == 0) continue;
        char buf[3] = { p.base91_alt_c, p.base91_alt_s, '\0' };
        int got = APRSPacketLib::decodeBase91EncodedAltitude(String(buf));
        char msg[128];
        snprintf(msg, sizeof(msg),
                 "%s: alt bytes \"%s\" expected ~%d m got %d m",
                 p.name, buf, p.altitude_m, got);
        // Encoding truncates log_1.002(altitude_ft) to int, then the
        // round-trip quantizes to a band ~0.2% wide. 5% + 1 m of
        // tolerance comfortably covers that without hiding bugs.
        int tol = (p.altitude_m / 20) + 1;
        TEST_ASSERT_INT_WITHIN_MESSAGE(tol, p.altitude_m, got, msg);
    }
}

// ---------- runner ----------

static void run_all(void) {
    RUN_TEST(test_decode_course_against_spec_vectors);
    RUN_TEST(test_decode_speed_against_spec_vectors);
    RUN_TEST(test_decode_lat_known_vectors);
    RUN_TEST(test_decode_lon_known_vectors);
    RUN_TEST(test_decode_lat_north_pole_exact);
    RUN_TEST(test_decode_lat_south_pole_exact);
    RUN_TEST(test_decode_altitude_known_vectors);
}

#ifdef NATIVE_TEST_BUILD
int main(int /*argc*/, char ** /*argv*/) {
    UNITY_BEGIN();
    run_all();
    return UNITY_END();
}
#else
void setup(void) {
    Serial.begin(115200);
    delay(2000);
    UNITY_BEGIN();
    run_all();
    UNITY_END();
}

void loop(void) {
    delay(1000);
}
#endif
