// Generated by tools/gen_aprs_vectors.py — DO NOT EDIT BY HAND.
//
// Source: APRS Protocol Reference v1.2 §9 ('Compressed Position
// Report Data Formats'). Each row is computed from the spec
// formulas; aprslib is consulted as a third-party cross-check.

#pragma once

struct CourseVector { char encoded; int course_deg; };
struct SpeedVector  { char encoded; int speed_kmh; };

// Full-packet vectors for the five fixed sites used by
// test_base91_encode and test_base91_roundtrip. Strings are
// 4 base-91 chars + null terminator.
struct Base91FixedPoint {
    const char* name;
    float       lat_deg;
    float       lon_deg;
    int         course_deg;
    int         speed_kn;
    int         altitude_m;
    int         altitude_ft;
    char        base91_lat[5];
    char        base91_lon[5];
    char        base91_c;
    char        base91_s;
    char        base91_alt_c;
    char        base91_alt_s;
};

static const char kBase91TByteCS  = 'G';
static const char kBase91TByteAlt = 'Q';

static const CourseVector kCourseVectors[] = {
    { '!'   ,   0 },
    { '7'   ,  88 },
    { ':'   , 100 },
    { 'N'   , 180 },
    { 'S'   , 200 },
    { 'z'   , 356 },
};

static const SpeedVector kSpeedVectors[] = {
    { '!'   ,   0 },
    { 'N'   ,  57 },
    { 'P'   ,  67 },
    { 'T'   ,  91 },
    { ']'   , 185 },
};

static const Base91FixedPoint kBase91FixedPoints[] = {
    { "Munich"     ,     48.138630f,     11.573410f,  90,  30,  525,  1722, "6/Y`"  , "QG2."  , '7'   , 'N'   , 'I'   , 'z'    },
    { "CapeTown"   ,    -33.918861f,     18.423300f, 180,  10,   25,    82, "_[9A"  , "S.cy"  , 'N'   , '@'   , '9'   , '6'    },
    { "Auckland"   ,    -36.848460f,    174.762189f, 270, 100,    0,     0, "a,#\\" , "z]Q9"  , 'e'   , ']'   , '!'   , '!'    },
    { "NorthPole"  ,     89.999000f,      0.000000f,   0,   0, 5000, 16404, "!!%2"  , "NN!!"  , '!'   , '!'   , 'V'   , 'C'    },
    { "Equator0"   ,      0.000000f,      0.000000f,   0,   0,    0,     0, "NN!!"  , "NN!!"  , '!'   , '!'   , '!'   , '!'    },
};
