// Generated by tools/gen_decode_vectors.py — DO NOT EDIT BY HAND.
//
// Source: APRS Protocol Reference v1.2 §9 'Course/Speed'.
//   c byte = chr(round(course_deg / 4) + 33)
//   s byte = chr(round(log_1.08(speed_kn + 1)) + 33)
//
// Each row was cross-checked against aprslib's parse() before commit.

#pragma once

struct CourseVector { char encoded; int course_deg; };
struct SpeedVector  { char encoded; int speed_kmh; };

static const CourseVector kCourseVectors[] = {
    { '!' ,   0 },
    { '7' ,  88 },
    { ':' , 100 },
    { 'N' , 180 },
    { 'S' , 200 },
    { 'z' , 356 },
};

static const SpeedVector kSpeedVectors[] = {
    { '!' ,   0 },
    { 'N' ,  57 },
    { 'P' ,  67 },
    { 'T' ,  91 },
    { ']' , 185 },
};
