#!/usr/bin/env python3
"""Generate (encoded byte, expected decode) vectors for the compressed
position c/s decoders.

Encoding follows APRS Protocol Reference v1.2 §9 ("Course/Speed"):

    c byte = chr(round(course_deg / 4) + 33)
    s byte = chr(round(log_1.08(speed_kn + 1)) + 33)

The companion decoders in src/APRSPacketLib.cpp invert these. Output is
a C header at test/common/decode_vectors.h that the Unity test in
test/test_base91_decode_course_speed/ consumes.

Each vector is cross-checked against aprslib (rossengeorgiev/aprs-python)
when that package is installed; the script aborts loudly if aprslib
disagrees with the spec formula, which would mean the generator itself
is wrong.

Re-run after editing COURSE_CASES_DEG or SPEED_CASES_KN:

    tools/.venv/bin/python tools/gen_decode_vectors.py
"""

from __future__ import annotations

import math
import sys
import warnings
from pathlib import Path

# aprslib 0.7.2 has unescaped backslashes in regex string literals that
# trigger SyntaxWarning under Python 3.12+. Upstream noise; filter it
# rather than relying on cached .pyc to hide it.
warnings.filterwarnings(
    "ignore",
    category=SyntaxWarning,
    message=r"invalid escape sequence",
)


COURSE_CASES_DEG = [0, 88, 100, 180, 200, 356]
SPEED_CASES_KN = [0, 30, 36, 50, 99]

OUT = Path(__file__).resolve().parent.parent / "test" / "common" / "decode_vectors.h"


def encode_course(course_deg: int) -> str:
    return chr(round(course_deg / 4) + 33)


def encode_speed(speed_kn: int) -> str:
    return chr(round(math.log(speed_kn + 1) / math.log(1.08)) + 33)


def decode_speed_kn(s_byte: str) -> float:
    """Spec-formula decode in knots, as a float (no rounding)."""
    return 1.08 ** (ord(s_byte) - 33) - 1


def decode_speed_kmh(s_byte: str) -> int:
    """Spec-formula decode rounded the way the C++ decoder rounds.

    The library returns `int` from a `double` expression — which in
    both C and Python truncates toward zero. Matching that here means
    the Unity test can assert exact equality with no tolerance.
    """
    return int(decode_speed_kn(s_byte) * 1.852)


def cross_check(course_vecs, speed_vecs) -> None:
    """Verify the spec formula matches aprslib for every vector."""
    try:
        import aprslib
    except ImportError:
        print(
            "WARN: aprslib not installed — skipping third-party cross-check.\n"
            "      Install with `uv pip install --python tools/.venv/bin/python aprslib`.",
            file=sys.stderr,
        )
        return

    # Pair each course vector with each speed vector to build a real
    # compressed packet. aprslib then returns its own decoded course
    # and speed, which must match the values we emitted.
    failures = []
    for c_byte, course_deg in course_vecs:
        for s_byte, speed_kmh in speed_vecs:
            packet = f"TEST>APRS:=/<<<<<<<<>{c_byte}{s_byte}G"
            parsed = aprslib.parse(packet)
            got_course = parsed.get("course")
            got_speed = parsed.get("speed")

            # APRS v1.2 reassigned encoded course 0 to mean "due north"
            # (= 360); 0 and 360 denote the same direction. Normalize.
            expected_course = 360 if course_deg == 0 else course_deg
            if got_course != expected_course:
                failures.append(
                    f"course byte {c_byte!r}: spec says {expected_course}°, "
                    f"aprslib says {got_course}°"
                )
            # aprslib returns the speed in km/h as a float; we compare
            # against the unrounded spec value to within machine epsilon
            # rather than against the int-truncated vector (otherwise
            # we'd flag the truncation step itself as disagreement).
            spec_kmh = decode_speed_kn(s_byte) * 1.852
            if got_speed is None or abs(got_speed - spec_kmh) > 1e-6:
                failures.append(
                    f"speed byte {s_byte!r}: spec says {spec_kmh} km/h, "
                    f"aprslib says {got_speed} km/h"
                )

    if failures:
        print("ERROR: spec-formula vectors disagree with aprslib:", file=sys.stderr)
        for f in failures:
            print(f"  - {f}", file=sys.stderr)
        sys.exit(1)


def emit_header(course_vecs, speed_vecs) -> None:
    lines = [
        "// Generated by tools/gen_decode_vectors.py — DO NOT EDIT BY HAND.",
        "//",
        "// Source: APRS Protocol Reference v1.2 §9 'Course/Speed'.",
        "//   c byte = chr(round(course_deg / 4) + 33)",
        "//   s byte = chr(round(log_1.08(speed_kn + 1)) + 33)",
        "//",
        "// Each row was cross-checked against aprslib's parse() before commit.",
        "",
        "#pragma once",
        "",
        "struct CourseVector { char encoded; int course_deg; };",
        "struct SpeedVector  { char encoded; int speed_kmh; };",
        "",
        "static const CourseVector kCourseVectors[] = {",
    ]
    for byte, course_deg in course_vecs:
        lines.append(f"    {{ {byte!r:<4}, {course_deg:>3} }},")
    lines.append("};")
    lines.append("")
    lines.append("static const SpeedVector kSpeedVectors[] = {")
    for byte, speed_kmh in speed_vecs:
        lines.append(f"    {{ {byte!r:<4}, {speed_kmh:>3} }},")
    lines.append("};")
    lines.append("")

    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT}", file=sys.stderr)


def main() -> int:
    course_vecs = [(encode_course(c), c) for c in COURSE_CASES_DEG]
    speed_vecs = [(encode_speed(s), decode_speed_kmh(encode_speed(s))) for s in SPEED_CASES_KN]
    cross_check(course_vecs, speed_vecs)
    emit_header(course_vecs, speed_vecs)
    return 0


if __name__ == "__main__":
    sys.exit(main())
